[phases.setup]
nixPkgs = [
  "python310",
  "python310Packages.pip",
  "gcc",
  "libffi",
  "openssl",
  "pkg-config"
]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "python main.py"
